use std::collections::BTreeMap;

use crate::compose::{Compose, ComposeError};
use crate::http::{Method, Request};
use crate::workspace::RequestDefinition;

pub fn to_curl(compose: &Compose) -> Result<String, ComposeError> {
    let req = compose.clone().build()?;
    Ok(curl_from_request(&req))
}

pub fn to_openapi_yaml(
    title: &str,
    requests: &[(String, RequestDefinition)],
) -> Result<String, serde_yaml::Error> {
    let mut paths = BTreeMap::<String, BTreeMap<String, OpenApiOperationOut>>::new();
    for (id, request) in requests {
        let (path, query_from_url) = openapi_path_and_query(&request.compose.url);
        let operation = operation_from_request(id, request, query_from_url);
        paths.entry(path).or_default().insert(
            method_str(request.compose.method).to_ascii_lowercase(),
            operation,
        );
    }

    serde_yaml::to_string(&OpenApiDoc {
        openapi: "3.0.3".into(),
        info: OpenApiInfoOut {
            title: title.to_string(),
            version: "1.0.0".into(),
        },
        paths,
    })
}

pub fn to_markdown_docs(title: &str, requests: &[(String, RequestDefinition)]) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {title} API\n\n"));
    out.push_str("Generated by StubHouse.\n\n");
    for (id, request) in requests {
        out.push_str(&format!("## {}\n\n", request.name));
        out.push_str(&format!("- ID: `{id}`\n"));
        out.push_str(&format!(
            "- Method: `{}`\n",
            method_str(request.compose.method)
        ));
        out.push_str(&format!("- URL: `{}`\n", request.compose.url));
        if !request.description.is_empty() {
            out.push_str(&format!("\n{}\n", request.description));
        }
        if !request.compose.query.is_empty() {
            out.push_str("\n### Query Parameters\n\n| Name | Value |\n|---|---|\n");
            for (name, value) in &request.compose.query {
                out.push_str(&format!(
                    "| `{}` | `{}` |\n",
                    escape_md(name),
                    escape_md(value)
                ));
            }
        }
        if !request.compose.headers.is_empty() {
            out.push_str("\n### Headers\n\n| Name | Value |\n|---|---|\n");
            for (name, value) in &request.compose.headers {
                out.push_str(&format!(
                    "| `{}` | `{}` |\n",
                    escape_md(name),
                    escape_md(value)
                ));
            }
        }
        match &request.compose.body {
            crate::compose::Body::None => {}
            crate::compose::Body::Json { text } => {
                out.push_str("\n### Body\n\n```json\n");
                out.push_str(text.trim());
                out.push_str("\n```\n");
            }
            crate::compose::Body::Text { content_type, text } => {
                out.push_str(&format!("\n### Body `{}`\n\n```text\n", content_type));
                out.push_str(text.trim());
                out.push_str("\n```\n");
            }
            crate::compose::Body::Form { fields } => {
                out.push_str("\n### Form Fields\n\n| Name | Value |\n|---|---|\n");
                for (name, value) in fields {
                    out.push_str(&format!(
                        "| `{}` | `{}` |\n",
                        escape_md(name),
                        escape_md(value)
                    ));
                }
            }
        }
        out.push('\n');
    }
    out
}

pub fn to_docker_compose(workspace_mount: &str, port: u16) -> Result<String, serde_yaml::Error> {
    #[derive(serde::Serialize)]
    struct ComposeFile {
        services: BTreeMap<String, Service>,
    }
    #[derive(serde::Serialize)]
    struct Service {
        image: String,
        command: Vec<String>,
        ports: Vec<String>,
        volumes: Vec<String>,
        working_dir: String,
    }

    serde_yaml::to_string(&ComposeFile {
        services: BTreeMap::from([(
            "stubhouse-mock".into(),
            Service {
                image: "ghcr.io/stubhouse/stubhouse:latest".into(),
                command: vec![
                    "stubhouse".into(),
                    "serve".into(),
                    "--workspace".into(),
                    "/workspace".into(),
                    "--bind".into(),
                    "0.0.0.0".into(),
                    "--port".into(),
                    port.to_string(),
                ],
                ports: vec![format!("{port}:{port}")],
                volumes: vec![format!("{workspace_mount}:/workspace:ro")],
                working_dir: "/workspace".into(),
            },
        )]),
    })
}

fn curl_from_request(req: &Request) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push("curl".into());

    if !matches!(req.method, Method::Get) {
        parts.push("-X".into());
        parts.push(method_str(req.method).into());
    }

    for (k, v) in &req.headers {
        parts.push("-H".into());
        parts.push(shell_quote(&format!("{k}: {v}")));
    }

    if let Some(body) = req.body.as_ref() {
        if !body.is_empty() {
            parts.push("--data-binary".into());
            // Body is a JSON/text/form payload — stringify with lossy UTF-8.
            // For true binary bodies users will need the file-upload path (post-v1).
            let s = String::from_utf8_lossy(body);
            parts.push(shell_quote(&s));
        }
    }

    parts.push(shell_quote(&req.url));
    parts.join(" ")
}

fn method_str(m: Method) -> &'static str {
    match m {
        Method::Get => "GET",
        Method::Post => "POST",
        Method::Put => "PUT",
        Method::Patch => "PATCH",
        Method::Delete => "DELETE",
        Method::Head => "HEAD",
        Method::Options => "OPTIONS",
    }
}

fn operation_from_request(
    id: &str,
    request: &RequestDefinition,
    query_from_url: Vec<(String, String)>,
) -> OpenApiOperationOut {
    let mut parameters = Vec::new();
    let mut query = query_from_url;
    query.extend(request.compose.query.clone());
    for (name, _) in query {
        if !name.is_empty() {
            parameters.push(OpenApiParameterOut {
                name,
                location: "query".into(),
                required: false,
                schema: OpenApiSchemaOut {
                    kind: "string".into(),
                },
            });
        }
    }
    for (name, _) in &request.compose.headers {
        if !name.eq_ignore_ascii_case("content-type") {
            parameters.push(OpenApiParameterOut {
                name: name.clone(),
                location: "header".into(),
                required: false,
                schema: OpenApiSchemaOut {
                    kind: "string".into(),
                },
            });
        }
    }

    OpenApiOperationOut {
        operation_id: slug_operation_id(id),
        summary: request.name.clone(),
        description: if request.description.is_empty() {
            None
        } else {
            Some(request.description.clone())
        },
        parameters,
        request_body: request_body_from_compose(&request.compose),
        responses: BTreeMap::from([(
            "200".into(),
            OpenApiResponseOut {
                description: "OK".into(),
            },
        )]),
    }
}

fn request_body_from_compose(compose: &Compose) -> Option<OpenApiRequestBodyOut> {
    let (content_type, example) = match &compose.body {
        crate::compose::Body::None => return None,
        crate::compose::Body::Json { text } => (
            "application/json".to_string(),
            serde_json::from_str::<serde_json::Value>(text)
                .unwrap_or_else(|_| serde_json::Value::Object(Default::default())),
        ),
        crate::compose::Body::Text { content_type, text } => (
            content_type.clone(),
            serde_json::Value::String(text.clone()),
        ),
        crate::compose::Body::Form { fields } => (
            "application/x-www-form-urlencoded".into(),
            serde_json::Value::Object(
                fields
                    .iter()
                    .map(|(key, value)| (key.clone(), serde_json::Value::String(value.clone())))
                    .collect(),
            ),
        ),
    };
    Some(OpenApiRequestBodyOut {
        content: BTreeMap::from([(
            content_type,
            OpenApiMediaTypeOut {
                example,
                schema: OpenApiSchemaOut {
                    kind: "object".into(),
                },
            },
        )]),
    })
}

fn openapi_path_and_query(url: &str) -> (String, Vec<(String, String)>) {
    match url::Url::parse(url) {
        Ok(parsed) => (
            parsed.path().to_string(),
            parsed
                .query_pairs()
                .map(|(key, value)| (key.into_owned(), value.into_owned()))
                .collect(),
        ),
        Err(_) => (url.split('?').next().unwrap_or(url).to_string(), vec![]),
    }
}

fn slug_operation_id(id: &str) -> String {
    let mut out = id
        .trim_end_matches(".yaml")
        .chars()
        .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
        .collect::<String>();
    while out.contains("__") {
        out = out.replace("__", "_");
    }
    out.trim_matches('_').to_string()
}

fn escape_md(s: &str) -> String {
    s.replace('|', "\\|").replace('`', "\\`")
}

#[derive(serde::Serialize)]
struct OpenApiDoc {
    openapi: String,
    info: OpenApiInfoOut,
    paths: BTreeMap<String, BTreeMap<String, OpenApiOperationOut>>,
}

#[derive(serde::Serialize)]
struct OpenApiInfoOut {
    title: String,
    version: String,
}

#[derive(serde::Serialize)]
#[serde(rename_all = "camelCase")]
struct OpenApiOperationOut {
    operation_id: String,
    summary: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    description: Option<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    parameters: Vec<OpenApiParameterOut>,
    #[serde(skip_serializing_if = "Option::is_none")]
    request_body: Option<OpenApiRequestBodyOut>,
    responses: BTreeMap<String, OpenApiResponseOut>,
}

#[derive(serde::Serialize)]
struct OpenApiParameterOut {
    name: String,
    #[serde(rename = "in")]
    location: String,
    required: bool,
    schema: OpenApiSchemaOut,
}

#[derive(serde::Serialize)]
struct OpenApiRequestBodyOut {
    content: BTreeMap<String, OpenApiMediaTypeOut>,
}

#[derive(serde::Serialize)]
struct OpenApiMediaTypeOut {
    schema: OpenApiSchemaOut,
    example: serde_json::Value,
}

#[derive(serde::Serialize)]
struct OpenApiSchemaOut {
    #[serde(rename = "type")]
    kind: String,
}

#[derive(serde::Serialize)]
struct OpenApiResponseOut {
    description: String,
}

/// POSIX-style single-quote escape. Safe for sh/bash/zsh.
fn shell_quote(s: &str) -> String {
    if !s.is_empty()
        && s.chars().all(|c| {
            c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '.' | '/' | ':' | ',' | '=' | '@')
        })
    {
        return s.to_string();
    }
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        if ch == '\'' {
            out.push_str("'\\''");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compose::{Auth, Body, Compose};
    use crate::workspace::RequestDefinition;

    fn base() -> Compose {
        Compose {
            method: Method::Get,
            url: "https://example.com/api".into(),
            query: vec![],
            headers: vec![],
            auth: Auth::None,
            body: Body::None,
        }
    }

    #[test]
    fn simple_get_omits_method_flag() {
        let s = to_curl(&base()).unwrap();
        assert_eq!(s, "curl https://example.com/api");
    }

    #[test]
    fn post_emits_method_flag() {
        let c = Compose {
            method: Method::Post,
            ..base()
        };
        let s = to_curl(&c).unwrap();
        assert!(s.contains("-X POST"));
    }

    #[test]
    fn headers_are_single_quoted() {
        let c = Compose {
            headers: vec![("X-Custom".into(), "hello world".into())],
            ..base()
        };
        let s = to_curl(&c).unwrap();
        assert!(s.contains("-H 'X-Custom: hello world'"), "got: {s}");
    }

    #[test]
    fn bearer_auth_appears_as_header() {
        let c = Compose {
            auth: Auth::Bearer {
                token: "abc.def".into(),
            },
            ..base()
        };
        let s = to_curl(&c).unwrap();
        assert!(s.contains("Authorization: Bearer abc.def"));
    }

    #[test]
    fn json_body_is_quoted_with_data_binary() {
        let c = Compose {
            method: Method::Post,
            body: Body::Json {
                text: r#"{"a":1,"b":"x y"}"#.into(),
            },
            ..base()
        };
        let s = to_curl(&c).unwrap();
        assert!(s.contains("--data-binary"), "got: {s}");
        assert!(s.contains(r#"'{"a":1,"b":"x y"}'"#), "got: {s}");
        assert!(s.contains("Content-Type: application/json"));
    }

    #[test]
    fn single_quotes_inside_body_are_escaped() {
        let c = Compose {
            method: Method::Post,
            body: Body::Json {
                text: r#"{"q":"O'Brien"}"#.into(),
            },
            ..base()
        };
        let s = to_curl(&c).unwrap();
        // POSIX trick: close, escape, reopen.
        assert!(s.contains(r#"O'\''Brien"#), "got: {s}");
    }

    #[test]
    fn query_params_round_trip_into_url() {
        let c = Compose {
            query: vec![("q".into(), "hello world".into())],
            ..base()
        };
        let s = to_curl(&c).unwrap();
        assert!(
            s.contains("q=hello+world") || s.contains("q=hello%20world"),
            "got: {s}"
        );
    }

    #[test]
    fn plain_url_is_not_quoted() {
        let s = to_curl(&base()).unwrap();
        assert!(s.ends_with(" https://example.com/api"), "got: {s}");
    }

    #[test]
    fn exports_openapi_yaml_for_requests() {
        let def = RequestDefinition {
            name: "Create user".into(),
            description: "Creates a user".into(),
            pre_request_script: None,
            post_response_script: None,
            compose: Compose {
                method: Method::Post,
                url: "https://api.example.com/users".into(),
                query: vec![("notify".into(), "true".into())],
                headers: vec![("X-Team".into(), "core".into())],
                auth: Auth::None,
                body: Body::Json {
                    text: r#"{"name":"Alice"}"#.into(),
                },
            },
        };
        let yaml =
            to_openapi_yaml("Demo", &[("collections/users/create.yaml".into(), def)]).unwrap();
        assert!(yaml.contains("openapi: 3.0.3"));
        assert!(yaml.contains("/users:"));
        assert!(yaml.contains("operationId: collections_users_create"));
        assert!(yaml.contains("application/json"));
        assert!(yaml.contains("notify"));
    }

    #[test]
    fn exports_markdown_docs_for_requests() {
        let def = RequestDefinition {
            name: "List users".into(),
            description: "Returns users".into(),
            pre_request_script: None,
            post_response_script: None,
            compose: Compose {
                query: vec![("limit".into(), "10".into())],
                ..base()
            },
        };
        let markdown = to_markdown_docs("Demo", &[("collections/users/list.yaml".into(), def)]);
        assert!(markdown.contains("# Demo API"));
        assert!(markdown.contains("## List users"));
        assert!(markdown.contains("collections/users/list.yaml"));
        assert!(markdown.contains("limit"));
    }

    #[test]
    fn exports_docker_compose_for_mock_service() {
        let yaml = to_docker_compose(".", 4010).unwrap();
        assert!(yaml.contains("stubhouse-mock"));
        assert!(yaml.contains("stubhouse"));
        assert!(yaml.contains("4010:4010"));
        assert!(yaml.contains(".:/workspace:ro"));
    }
}
